apiVersion: v1
kind: Service
metadata:
  name: demo-backend
  labels:
    app: demo-backend
  namespace: data-transfer
spec:
  selector:
    app: demo-backend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31003
    protocol: TCP
  type: NodePort
