apiVersion: v1
kind: Service
metadata:
  name: demo-frontend
  labels:
    app: demo-frontend
  namespace: data-transfer
spec:
  selector:
    app: demo-frontend
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 31002
  type: NodePort
